name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@1.9.4
        with:
          feed_list: "https://dhanur.me/rss.xml"
          max_post_count: 5
          user_agent: "dhanur-gh-action-secret-99@MvK7eT1ACR#C"
