name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Temporarily Bypass Cloudflare BFM
        uses: xiaotianxt/bypass-cloudflare-for-github-action@v2.1.0
        with:
          cf_account_id: ${{ secrets.CF_ACCOUNT_ID }}
          cf_zone_id: ${{ secrets.CF_ZONE_ID }}
          cf_api_token: ${{ secrets.CF_API_TOKEN }}
          disable_bot_fight_mode: true

      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@1.9.4
        with:
          feed_list: "https://dhanur.me/rss.xml"
          max_post_count: 5
